# Generated by Django 4.2.7 on 2023-11-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='create_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='delete_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='update_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
