# Generated by Django 4.2.7 on 2023-12-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=15)),
                ('course_fee', models.CharField(blank=True, max_length=15)),
                ('course_description', models.CharField(blank=True, max_length=15)),
                ('is_paid', models.BooleanField(default=True)),
                ('course_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
