# Generated by Django 4.2.7 on 2023-12-04 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_course_pic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Courses',
        ),
    ]
