# Generated by Django 4.2.7 on 2023-12-05 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_courses_slug_alter_courses_course_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='slug',
            new_name='s',
        ),
    ]
