# Generated by Django 4.2.7 on 2023-12-06 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_slug_courses_s'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='s',
        ),
    ]
