# Generated by Django 4.2.7 on 2023-12-08 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_courses_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='slug',
            new_name='slugs',
        ),
    ]
