# Generated by Django 4.2.7 on 2023-12-08 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_slug_courses_slugs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='slugs',
            new_name='slug',
        ),
    ]
