# Generated by Django 4.2.7 on 2023-12-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_slugs_courses_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
