# Generated by Django 4.2.7 on 2023-12-08 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_courses_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=50)),
                ('video_upload_url', models.CharField(max_length=250)),
                ('duration', models.CharField(max_length=20)),
                ('thumbnail', models.CharField(max_length=250)),
                ('note', models.TextField()),
                ('video_file', models.CharField(max_length=250)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.lessons')),
            ],
        ),
    ]
