# Generated by Django 4.2.7 on 2023-12-08 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_lessons_slug_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='slug',
        ),
    ]
