# Generated by Django 4.2.7 on 2023-12-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_lessons_id_alter_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(null=True, upload_to='videos/', verbose_name='Video file'),
        ),
    ]
