# Generated by Django 4.2.7 on 2023-12-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_courses_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.CharField(help_text='Thumbnail location name', max_length=250),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.CharField(help_text='Video location name', max_length=250),
        ),
    ]
