# Generated by Django 4.2.7 on 2023-12-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_video_thumbnail_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_upload_url',
            field=models.CharField(help_text='Video url', max_length=250),
        ),
    ]
