# Generated by Django 4.2.7 on 2023-12-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='review_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
